//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoologico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Enfermeria
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Animal")]
        public int IdAnimal { get; set; }
        [Required]
        [Display(Name = "Fecha Ingreso")]
        public System.DateTime FechaIngreso { get; set; }
        [Required]
        [Display(Name = "Diagnóstico")]
        public string Diagnostico { get; set; }
    
        public virtual Animales Animales { get; set; }
    }
}
