//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoologico.Models
{

    public partial class Reporte
    {
        public string Nombre { get; set; }
        public int Edad { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string Diagnostico { get; set; }
    }
}
